# Generated by Django 3.0.5 on 2021-02-14 08:18

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210214_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Lenovo\\Desktop\\Secura-Drive\\secura_drivefiles/', collection='files'), upload_to='uploads/'),
        ),
    ]
