# Generated by Django 3.0.5 on 2021-02-14 09:56

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210214_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(storage=djongo.storage.GridFSStorage(collection='files'), upload_to=''),
        ),
    ]
