# Generated by Django 3.0.5 on 2021-02-14 10:03

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210214_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Lenovo\\Desktop\\Secura-Drive\\secura_drivemyfiles/', collection='files'), upload_to=''),
        ),
    ]
