# Generated by Django 3.0.5 on 2021-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210214_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_content_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(),
        ),
    ]
